[build]
  command = "npm install && npm run build:client"
  publish = "dist/public"
  base = "."

[dev]
  framework = "vite"
  target = "dist/public"
  command = "npm run dev"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = false  # Disable CI to prevent build failures

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
